import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navBar";
import Footer from "./components/footer";
import { ShopingCartContextProvider } from "@/context/ShopingCartContext";
import ProgressBar from "./components/progressBar";

export const metadata: Metadata = {
  title: {
    default: "NextMerce",
    template: "NextMerce | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fa" dir="rtl">
      <body className="relative bg-gradient-to-br from-[#e4d0ff] via-[#d0f0ff] to-[#d0ffe5]">
        <ShopingCartContextProvider >
          <ProgressBar />
          <NavBar />
          {children}
          <Footer />
        </ShopingCartContextProvider>
      </body>
    </html>
  );

}
